CREATE TABLE person(
  person_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
  name varchar(255) NOT NULL CHECK ( length(name)>3 ),
  username varchar(255) NOT NULL UNIQUE CHECK ( length(username)>3 ),
  password varchar(255) NOT NULL CHECK ( length(password)>3 ),
  age int CHECK ( age>1 AND age<125),
  role varchar(255) NOT NULL CHECK ( length(role)>3 )
);